### ISSUE TITLE
java.lang.IllegalStateException error when opening a notification on android

### ISSUE THREAD

**Issue by mauriciosabogal** [Plotprojects/plot-titanium-module#10]
Hi, I'm using the Android-2.2.0 version with Titanium SDK 7.0.1.GA, when I open a notification the application throws this error:

```
[ERROR] E/Plot Test/Plot: Failed to retrieve sent notifications
[ERROR] E/Plot Test/Plot: java.lang.IllegalStateException: Cannot call this method from the main thread. Use a background thread or an AsyncTask to prevent blocking the main thread.
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.internal.f.c.a(SourceFile:1055)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.c.a(SourceFile:204)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.c.j(SourceFile:226)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.j.j(SourceFile:180)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.Plot.getSentNotifications(SourceFile:559)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.titanium.PlotAndroidModule.getSentNotifications(PlotAndroidModule.java:273)
[ERROR] E/Plot Test/Plot: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[ERROR] E/Plot Test/Plot: 	at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[ERROR] E/Plot Test/Plot: 	at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:936)
[ERROR] E/Plot Test/Plot: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1159)
[ERROR] E/Plot Test/Plot: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] E/Plot Test/Plot: 	at android.os.Looper.loop(Looper.java:234)
[ERROR] E/Plot Test/Plot: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
[ERROR] E/Plot Test/Plot: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] E/Plot Test/Plot: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[ERROR] E/Plot Test/Plot: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
[ERROR] E/Plot Test/Plot: Failed to retrieve loaded geotriggers
[ERROR] E/Plot Test/Plot: java.lang.IllegalStateException: Cannot call this method from the main thread. Use a background thread or an AsyncTask to prevent blocking the main thread.
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.internal.f.c.a(SourceFile:1055)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.c.a(SourceFile:204)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.c.h(SourceFile:216)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.j.h(SourceFile:150)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.Plot.getLoadedGeotriggers(SourceFile:540)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.titanium.PlotAndroidModule.getLoadedGeotriggers(PlotAndroidModule.java:268)
[ERROR] E/Plot Test/Plot: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[ERROR] E/Plot Test/Plot: 	at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[ERROR] E/Plot Test/Plot: 	at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:936)
[ERROR] E/Plot Test/Plot: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1159)
[ERROR] E/Plot Test/Plot: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] E/Plot Test/Plot: 	at android.os.Looper.loop(Looper.java:234)
[ERROR] E/Plot Test/Plot: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
[ERROR] E/Plot Test/Plot: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] E/Plot Test/Plot: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[ERROR] E/Plot Test/Plot: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
[ERROR] E/Plot Test/Plot: Failed to retrieve sent geotriggers
[ERROR] E/Plot Test/Plot: java.lang.IllegalStateException: Cannot call this method from the main thread. Use a background thread or an AsyncTask to prevent blocking the main thread.
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.internal.f.c.a(SourceFile:1055)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.c.a(SourceFile:204)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.c.i(SourceFile:221)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.j.i(SourceFile:170)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.Plot.getSentGeotriggers(SourceFile:577)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.titanium.PlotAndroidModule.getSentGeotriggers(PlotAndroidModule.java:278)
[ERROR] E/Plot Test/Plot: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[ERROR] E/Plot Test/Plot: 	at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[ERROR] E/Plot Test/Plot: 	at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:936)
[ERROR] E/Plot Test/Plot: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1159)
[ERROR] E/Plot Test/Plot: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] E/Plot Test/Plot: 	at android.os.Looper.loop(Looper.java:234)
[ERROR] E/Plot Test/Plot: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
[ERROR] E/Plot Test/Plot: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] E/Plot Test/Plot: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[ERROR] E/Plot Test/Plot: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
[ERROR] E/Plot Test/Plot: Failed to retrieve loaded notifications
[ERROR] E/Plot Test/Plot: java.lang.IllegalStateException: Cannot call this method from the main thread. Use a background thread or an AsyncTask to prevent blocking the main thread.
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.internal.f.c.a(SourceFile:1055)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.c.a(SourceFile:204)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.c.g(SourceFile:212)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.j.g(SourceFile:160)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.retail.android.Plot.getLoadedNotifications(SourceFile:525)
[ERROR] E/Plot Test/Plot: 	at com.plotprojects.titanium.PlotAndroidModule.getLoadedNotifications(PlotAndroidModule.java:263)
[ERROR] E/Plot Test/Plot: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[ERROR] E/Plot Test/Plot: 	at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[ERROR] E/Plot Test/Plot: 	at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:936)
[ERROR] E/Plot Test/Plot: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1159)
[ERROR] E/Plot Test/Plot: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] E/Plot Test/Plot: 	at android.os.Looper.loop(Looper.java:234)
[ERROR] E/Plot Test/Plot: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
[ERROR] E/Plot Test/Plot: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] E/Plot Test/Plot: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[ERROR] E/Plot Test/Plot: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
Hers's the app folder of my Titanium application
[app.zip](https://github.com/Plotprojects/plot-titanium-module/files/1817382/app.zip)

**Comment by andrebsampaio** [comment]
Hi Mauricio,
Running the methods plot.getLoadedNotifications() and plot.getLoadedGeotriggers() using a [ti.worker](https://github.com/appcelerator-modules/ti.worker) should solve the issue, considering that the problem is related to running these methods in the main thread as the stack trace shows.

**Comment by mauriciosabogal** [comment]
Hi @andrebsampaio, we are not using those methods getLoadedNotifications() and getLoadedGeotriggers(), we are just initializing plot and log in the console the data from the notification. The app throws that error when we tap on the notification. Here`s how we are doing the setup for the module:

```javascript
var TAG = '[index]';
var plot = require('com.plotprojects.ti');

var plotListener = onPlotNotification(notifyData) {
	setTimeout(function () {
		console.log(TAG, 'onPlotNotification: ' + JSON.stringify(notifyData));
	}, 0);
}

console.info('App ready');
plot.addEventListener("plotNotificationReceived", plotListener);

plot.initPlot({ notificationFilterEnabled: false });
```

Regarding ti.worker it seems to work only with iOS and the actual problem we have is happening on Android. 😟

Thank you

**Comment by mauriciosabogal** [comment]
We change these lines on `PlotAndroidModule.java` on the module to return an empty Array and the error is gone:

```java
  @Kroll.getProperty @Kroll.method
  public HashMap[] getLoadedNotifications() {
  	return JsonUtil.notificationTriggersToMap(new ArrayList());
  }
  
  @Kroll.getProperty @Kroll.method
  public HashMap[] getLoadedGeotriggers() {
  	return JsonUtil.geotriggersToMap(new ArrayList());
  }
  
  @Kroll.getProperty @Kroll.method
  public HashMap[] getSentNotifications() {
  	return JsonUtil.sentNotificationsToMap(new ArrayList());
  }
    
  @Kroll.getProperty @Kroll.method
  public HashMap[] getSentGeotriggers() {
  	return JsonUtil.sentGeotriggersToMap(new ArrayList());
  }
```

**Comment by andrebsampaio** [comment]
Hi @mauriciosabogal, I had a closer look and indeed there's an issue with the notification handler.
We're working on a fix for the next release. Thanks for reporting the problem!
Any further questions, send an email with your app name (as in the Plot dashboard) in the subject to csm-team@plotprojects.com.

Cheers

**Comment by pyotrli** [comment]
Hi @mauriciosabogal 

Can you please email us on csm-team@plotprojects.com and let us know which app you are working on? This is important and will help us progress this issue faster. 

Thank you.
